[behave]
stderr_capture = False
stdout_capture = False

[behave.formatters]
allure = allure_behave.formatter:AllureFormatter

;[behave.userdata]
;AllureFormatter.hide_excluded = True
;hide_excluded = True
